Repository timeplus-io/proton, pull requests merged in 2023-12, with the labels that each got.

#392 specify the data gen image version
  .github/workflows/proton_ci.yml
  examples/fraud_detection/docker-compose.yml
Labels: enhancement

#303 expose read metrics of external streams to the current prometheus endpoint
  programs/server/config.yaml
  src/Server/HTTPHandlerFactory.cpp
  src/Server/PrometheusMetricsWriter.cpp
  src/Server/PrometheusMetricsWriter.h
  src/Server/PrometheusRequestHandler.cpp
  src/Storages/ExternalStream/ExternalStreamCounter.h
  src/Storages/ExternalStream/Kafka/Kafka.cpp
  src/Storages/ExternalStream/Kafka/Kafka.h
  src/Storages/ExternalStream/Kafka/KafkaSource.cpp
  src/Storages/ExternalStream/Kafka/KafkaSource.h
  src/Storages/ExternalStream/StorageExternalStream.cpp
  src/Storages/ExternalStream/StorageExternalStream.h
  src/Storages/ExternalStream/StorageExternalStreamImpl.h
Labels: pr-test

#399 feat: manage format schemas with SQL.
  src/Access/Common/AccessType.h
  src/Access/tests/gtest_access_rights_ops.cpp
  src/Common/ErrorCodes.cpp
  src/Formats/FormatFactory.cpp
  src/Formats/FormatFactory.h
  src/Formats/FormatSchemaFactory.cpp
  src/Formats/FormatSchemaFactory.h
  src/Formats/ProtobufReader.cpp
  src/Formats/ProtobufReader.h
  src/Formats/ProtobufSchemas.cpp
  src/Formats/ProtobufSchemas.h
  src/Interpreters/InterpreterCreateFormatSchemaQuery.cpp
  src/Interpreters/InterpreterCreateFormatSchemaQuery.h
  src/Interpreters/InterpreterDropFormatSchemaQuery.cpp
  src/Interpreters/InterpreterDropFormatSchemaQuery.h
  src/Interpreters/InterpreterFactory.cpp
  src/Interpreters/InterpreterShowCreateFormatSchemaQuery.cpp
  src/Interpreters/InterpreterShowCreateFormatSchemaQuery.h
  src/Interpreters/InterpreterShowFormatSchemasQuery.cpp
  src/Interpreters/InterpreterShowFormatSchemasQuery.h
  src/Parsers/ASTCreateFormatSchemaQuery.cpp
  src/Parsers/ASTCreateFormatSchemaQuery.h
  src/Parsers/ASTDropFormatSchemaQuery.cpp
  src/Parsers/ASTDropFormatSchemaQuery.h
  src/Parsers/ASTShowCreateFormatSchemaQuery.cpp
  src/Parsers/ASTShowCreateFormatSchemaQuery.h
  src/Parsers/ASTShowFormatSchemasQuery.cpp
  src/Parsers/ASTShowFormatSchemasQuery.h
  src/Parsers/ParserCreateFormatSchemaQuery.cpp
  src/Parsers/ParserCreateFormatSchemaQuery.h
  src/Parsers/ParserDropFormatSchemaQuery.cpp
  src/Parsers/ParserDropFormatSchemaQuery.h
  src/Parsers/ParserQuery.cpp
  src/Parsers/ParserQueryWithOutput.cpp
  src/Parsers/ParserShowCreateFormatSchemaQuery.cpp
  src/Parsers/ParserShowCreateFormatSchemaQuery.h
  src/Parsers/ParserShowFormatSchemasQuery.cpp
  src/Parsers/ParserShowFormatSchemasQuery.h
  src/Processors/Formats/ISchemaWriter.h
  src/Processors/Formats/Impl/ProtobufRowInputFormat.cpp
  src/Processors/Formats/Impl/ProtobufRowInputFormat.h
  src/Storages/ExternalStream/ExternalStreamSettings.h
  src/Storages/ExternalStream/Kafka/Kafka.cpp
  src/Storages/ExternalStream/Kafka/Kafka.h
  src/Storages/ExternalStream/Kafka/KafkaSink.cpp
  src/Storages/ExternalStream/Kafka/KafkaSource.cpp
  src/Storages/ExternalStream/Log/FileLog.cpp
  src/Storages/ExternalStream/Log/FileLog.h
  src/Storages/ExternalStream/StorageExternalStreamImpl.h
  tests/stream/test_stream_smoke/0013_changelog_stream13.yaml
  tests/stream/test_stream_smoke/0033_format_schema.yaml
Labels: external stream, feature

#457 fix random stream eps incorrect
  src/Storages/Streaming/StorageRandom.cpp
Labels: bug
